site_name: Common Fund Data Ecosystem Documentation

theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.instant
  logo: images/CFDE-logo-white-outline.png
  favicon: images/CFDE-logo-white-outline.png
  docs_dir: docs
  custom_dir: custom

markdown_extensions:
- admonition
- pymdownx.emoji
- codehilite:
    guess_lang: false
- toc:
    permalink: true
extra:
  hypothesis: true
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:CFDE-HelpDesk%20<support@cfde.atlassian.net>
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CfdeNih
    - icon: fontawesome/brands/github
      link: https://github.com/nih-cfde/published-documentation
extra_css:
  - stylesheets/extra.css
plugins:
  - mkdocs-jupyter:
      include_source: True
#  - htmlproofer
  - exclude:
      glob:
        - the-fair-cookbook/content/1/testnb/*
        - specifications-and-documentation/README.md
  - search: # necessary for search to work
      separator: '[\s\-\.]+'
  - awesome-pages:
      collapse_single_pages: true
